// This Jenkinsfile is used by Jenkins to run the 'APICURON Exporter' step of Reactome's release.
// It requires that the 'GraphImporter' step has been run successfully before it can be run.

import org.reactome.release.jenkins.utilities.Utilities

// Shared library maintained at 'release-jenkins-utils' repository.
def utils = new Utilities()

pipeline {
    agent any
    // Set output folder where files generated by step will be stored.
    environment {
        OUTPUT_FOLDER = "apicuron_output"
    }

    stages {
        // This stage checks that upstream project 'DiagramConverter' was run successfully.
        stage('Check GenerateGraphDatabaseAndAnalysisCore build succeeded') {
            steps {
                script {
                    utils.checkUpstreamBuildsSucceeded("GenerateGraphDatabase")
                }
            }
        }
        // This stage builds the jar file using maven.
        stage('Setup: Build jar file') {
            steps {
                script {
                    sh "mvn clean package -DskipTests"
                }
            }
        }
        // Execute the jar file, producing a bulk upload to APICURON
        stage('Main: Run apicuron-Exporter') {
            steps {
                script {
                    sh "mkdir -p ${env.OUTPUT_FOLDER}"
                    sh "rm -f ${env.OUTPUT_FOLDER}/*"
                    withCredentials([file(credentialsId: 'Config', variable: 'CONFIG_FILE')]) {
                        def props = readProperties file: CONFIG_FILE
                        withEnv([
                            "DB_URI=bolt://${props.neo4jHostName}:${props.neo4jPort}",
                            "DB_NAME=${props.neo4jDbName}",
                            "DB_USER=${props.neo4jUserName}",
                            "DB_PASS=${props.neo4jPassword}",
                            "AC_SERVER=${props.apicuronServer}",
                            "AC_KEY=${props.apicuronKey}"
                        ]) {
                            sh 'java -Xmx"${JAVA_MEM_MAX}"m -jar target/apicuron-exporter-exec.jar \
                                --uri "$DB_URI" \
                                --database "$DB_NAME" \
                                --user "$DB_USER" \
                                --password "$DB_PASS" \
                                --server "$AC_SERVER" \
                                --key "$AC_KEY" \
                                --output "${OUTPUT_FOLDER}/report.json"'
                        }
                    }
                }
            }
        }
    }
}
