spring.neo4j.uri=${uri:}
spring.data.neo4j.database=${database:}
spring.neo4j.authentication.username=${user:}
spring.neo4j.authentication.password=${password:}

spring.main.web-application-type=none
spring.main.banner-mode=off

spring.main.allow-bean-definition-overriding=true

apicuron.key=${key:}
apicuron.server=${server:}
apicuron.output=${output:target/reports.json}